<#
.SYNOPSIS
Generates `Install-AksEeUpgrade.ps1` by embedding `worker.ps1` into
`launcher-template.ps1` at the `__EMBEDDED_WORKER_PS1__` sentinel, and emits a
minified variant for Arc Run Command delivery.

.DESCRIPTION
Run this after editing `worker.ps1` or `launcher-template.ps1`. Output is a
self-contained launcher that the operator runs directly on a VM or that
scalekit delivers via Arc run-command. Both the full and minified launchers are
parse-checked. The minified one is also size-checked against the runCommands
inline-script limit.

.PARAMETER ScriptDir
Directory containing the two source files. Defaults to the directory containing
this script. Pass an ABSOLUTE path: a relative ScriptDir mis-resolves the
sources and the parse check falsely errors.

.EXAMPLE
    .\Build-Launcher.ps1
#>

[CmdletBinding()]
param(
    [string]$ScriptDir = $PSScriptRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$templatePath = Join-Path $ScriptDir 'launcher-template.ps1'
$workerPath   = Join-Path $ScriptDir 'worker.ps1'
$outputPath   = Join-Path $ScriptDir 'Install-AksEeUpgrade.ps1'

foreach ($p in @($templatePath, $workerPath)) {
    if (-not (Test-Path $p)) { throw "Missing source: $p" }
}

$template = Get-Content -Raw -Path $templatePath
$worker   = Get-Content -Raw -Path $workerPath

# Defensive: a closing here-string terminator inside the embedded worker would
# break the generated launcher.
if ([regex]::IsMatch($worker, '(?m)^''@')) {
    throw "worker.ps1 contains a literal '@ at column 0, which would terminate the embedded here-string. Re-author to avoid that pattern."
}

# Trim a single trailing newline so the embedded content does not introduce an
# extra blank line before the closing '@.
$worker = $worker.TrimEnd("`r", "`n")

# MatchEvaluator so $-substitutions in the worker are not interpreted as regex
# back-references during replacement.
$rendered = [regex]::Replace(
    $template,
    '__EMBEDDED_WORKER_PS1__',
    { param($match) return $worker })

$banner = @"
# ============================================================================
# DO NOT EDIT THIS FILE.
# Generated by Build-Launcher.ps1 from:
#   - launcher-template.ps1
#   - worker.ps1
# Edit those sources and re-run Build-Launcher.ps1 to regenerate.
# ============================================================================

"@
$rendered = $banner + $rendered

Set-Content -Path $outputPath -Value $rendered -Encoding UTF8

$tokens = $null; $errors = $null
[System.Management.Automation.Language.Parser]::ParseFile($outputPath, [ref]$tokens, [ref]$errors) | Out-Null
if ($errors.Count -gt 0) {
    Write-Error 'Generated launcher has parse errors:'
    $errors | ForEach-Object { Write-Error "  $($_.Extent.StartLineNumber):$($_.Extent.StartColumnNumber)  $($_.Message)" }
    throw 'Parse check failed. Inspect Install-AksEeUpgrade.ps1.'
}

$lines = (Get-Content -Path $outputPath).Count
Write-Host "Generated $outputPath ($lines lines, parse OK)"

# Minified variant for Arc Run Command delivery. The runCommands API enforces a
# size limit on the inline script body, and JSON encoding plus request overhead
# push the wire size above the raw script size. Strip comments, blank lines, and
# leading whitespace to stay within the limit. Long-term scalability fix:
# `scriptUri` (a blob URL), which removes the inline size ceiling.
$minPath = Join-Path $ScriptDir 'Install-AksEeUpgrade.min.ps1'

function script:Compact-PSSource {
    param([string]$Source)
    $s = [regex]::Replace($Source, '(?s)<#.*?#>', '')
    $kept = New-Object System.Collections.Generic.List[string]
    foreach ($line in ($s -split "`r?`n")) {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*$') { continue }
        $kept.Add($line.Trim())
    }
    return ($kept -join "`n")
}

# The per-file minifier strips leading whitespace and would corrupt here-string
# bodies. worker.ps1 must not contain a here-string opener. A here-string opener
# (`@"` or `@'`) is always the last token on its line, so match it anywhere on a
# line, not only at column 0, to catch indented openers too.
if ($worker -match "(?m)@['""]\s*$") {
    throw "worker.ps1 contains a here-string opener. The per-file minifier strips leading whitespace and can silently corrupt here-string bodies. Either remove the here-string from worker.ps1 or upgrade Compact-PSSource to skip string tokens."
}

$minLauncherWrapper = script:Compact-PSSource $template
$minWorker          = script:Compact-PSSource $worker

$minified = [regex]::Replace(
    $minLauncherWrapper,
    '__EMBEDDED_WORKER_PS1__',
    { param($match) return $minWorker })

$minBanner = '# Generated minified launcher. Edit Build-Launcher.ps1 sources, not this file.'
$minContent = $minBanner + "`n" + $minified

# WriteAllText keeps the LF bytes verbatim (Set-Content appends CRLF). The
# minified launcher is pinned to LF in .gitattributes.
[System.IO.File]::WriteAllText($minPath, $minContent, [System.Text.UTF8Encoding]::new($true))

$minTokens = $null; $minErrors = $null
[System.Management.Automation.Language.Parser]::ParseFile($minPath, [ref]$minTokens, [ref]$minErrors) | Out-Null
if ($minErrors.Count -gt 0) {
    Write-Error 'Minified launcher has parse errors:'
    $minErrors | ForEach-Object { Write-Error "  $($_.Extent.StartLineNumber):$($_.Extent.StartColumnNumber)  $($_.Message)" }
    throw 'Minified parse check failed. Inspect Install-AksEeUpgrade.min.ps1.'
}

$minBytes = (Get-Item $minPath).Length
$minLines = (Get-Content $minPath).Count
Write-Host ("Generated {0} ({1} lines, {2:N0} bytes, parse OK)" -f $minPath, $minLines, $minBytes)
if ($minBytes -gt 36000) {
    Write-Warning ("Minified launcher is {0:N0} bytes and is approaching the runCommands inline-script size limit. Slim the source or move to scriptUri delivery before it grows further." -f $minBytes)
}
