FROM ubuntu.azurecr.io/ubuntu:noble@sha256:5ce7043d3beb84e91bfeecacb5fafc80602bf247a1dd6016bc0fe7d69d707eca

RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends python3 python3-venv

USER 65534:65534
ENV PYTHONDONTWRITEBYTECODE=1
